name: kart
description: Taste and smell dart a little like Kotlin. We can feel magic of Kotin even in dart.
version: 1.0.7
homepage: https://github.com/OpenFlutter/kart

environment:
  sdk: '>=2.16.2 <4.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
